---
# AWX Example Inventory
# This is a sample inventory file for AWX/Ansible Tower

all:
  children:
    # Web Servers Group
    webservers:
      hosts:
        web01:
          ansible_host: 192.168.1.10
          ansible_user: admin
          http_port: 80
          https_port: 443
        web02:
          ansible_host: 192.168.1.11
          ansible_user: admin
          http_port: 80
          https_port: 443
      vars:
        ansible_connection: ssh
        ansible_python_interpreter: /usr/bin/python3
        app_env: production
    
    # Database Servers Group
    dbservers:
      hosts:
        db01:
          ansible_host: 192.168.1.20
          ansible_user: admin
          db_port: 5432
          db_type: postgresql
        db02:
          ansible_host: 192.168.1.21
          ansible_user: admin
          db_port: 5432
          db_type: postgresql
      vars:
        ansible_connection: ssh
        ansible_python_interpreter: /usr/bin/python3
        app_env: production
    
    # Load Balancers Group
    loadbalancers:
      hosts:
        lb01:
          ansible_host: 192.168.1.30
          ansible_user: admin
          lb_algorithm: roundrobin
      vars:
        ansible_connection: ssh
        ansible_python_interpreter: /usr/bin/python3
    
    # Development Environment
    development:
      children:
        dev_webservers:
          hosts:
            dev-web01:
              ansible_host: 192.168.2.10
              ansible_user: developer
            dev-web02:
              ansible_host: 192.168.2.11
              ansible_user: developer
          vars:
            app_env: development
            debug_mode: true
        
        dev_dbservers:
          hosts:
            dev-db01:
              ansible_host: 192.168.2.20
              ansible_user: developer
              db_type: postgresql
          vars:
            app_env: development
      vars:
        ansible_connection: ssh
        ansible_python_interpreter: /usr/bin/python3
    
    # Production Environment
    production:
      children:
        webservers:
        dbservers:
        loadbalancers:
      vars:
        app_env: production
        backup_enabled: true
        monitoring_enabled: true

  vars:
    # Global variables for all hosts
    ansible_port: 22
    ntp_server: pool.ntp.org
    timezone: Europe/Warsaw
